services:
  db:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - my-postgres-data:/var/lib/postgresql/data

volumes:
  my-postgres-data: